### ISSUE TITLE
User request for help with image scaling modification

### ISSUE THREAD

**Issue by kathys** [davidh-ssec/polar2grid#102]
Got this email from Ron Godson (Environment Canada).  I was not sure of the best way to help, so I defer to you Dave.

From: "Goodson,Ron [Edm]" <Ron.Goodson@EC.gc.ca>
Subject: rescaling data in polar2grid
Date: August 27, 2014 at 10:32:30 AM CDT
To: "Kathy Strabala" <kathys@ssec.wisc.edu>

Hi Kathy.
 
I’m not sure if there is an official e-mail address where I should be asking the following question.  If so, please let me know what it might be.
 
Otherwise….
 
We currently create our 8-bit IR geotiff imagery with a linear enhancement between -80 -> +50.  I can see that there is a facility within polar2grid to do this
                http://www.ssec.wisc.edu/software/polar2grid/rescaling.html#backend-scaling-functions
but am unsure how I can specify it .. or what scripts I might have to modify to force the behavior I desire.
 
Is there a section of the documentation that describes how to modify either glue scripts .. or how to modify call to the back-ends scripts to change the default behavior for scaling?
 
Thanks very much.
 
ron

**Comment by davidh-ssec** [comment]
In polar2grid v2.0 (coming soon) I have changed rescaling configuration files to be simpler and more flexible. However, this means that this user would have to redo their custom configuration. The steps would be basically the same:

 1. Copy the current rescaling configuration (one file for all data types and configurations). A copy can be found [here](https://raw.githubusercontent.com/davidh-ssec/polar2grid/develop/py/polar2grid_core/polar2grid/core/rescale_configs/rescale.ini).
 2. Modify the section titled `rescale:default_btemp` so that it looks like this:
    ```
    [rescale:default_btemp]
    data_kind=brightness_temperature
    method=linear
    min_in=193.15
    max_in=323.15
    ```

 3. Specify the config file when running viirs2gtiff.sh with `--rescale-configs /path/to/my_rescale.ini`.

I have not written documentation for doing this on the official documentation site yet, but this method can be used for doing product specific scalings (or other identifying information) by providing a `product_name=i01` option in the config section for more control.
