### ISSUE TITLE
POLAR2GRID_GRID_COVERAGE question

### ISSUE THREAD

**Issue by kathys** [davidh-ssec/polar2grid#104]
Received email from user Ron Goodson, Environment Canada.  Can you help?

From: "Goodson,Ron [Edm]" <Ron.Goodson@EC.gc.ca>
Subject: POLAR2GRID_GRID_COVERAGE question
Date: September 19, 2014 at 2:57:02 PM CDT
To: <kathys@ssec.wisc.edu>

Hi
 
A quesion from your Northern Neighbour .. who uses polar-stereographic grids a lot..
 
I see the documentation says:
 
POLAR2GRID_GRID_COVERAGE
The value used to determine whether a grid is useful or not. Should be the minimum ratio of data area to grid area. So the default is "0.1"for 10%
 
Which I tried and tried and tried to set to a bigger value without success.  But digging deeper, I see the source code says…
 
----------------------------------------------------------------------------------------------------
 
def  determine_grid_coverage( blah blah blah)
 
<..snip..>
 
.. warning::
 
This will not work with grids or data covering the poles
 
 
Do I take this to mean that .. since, by definition, the origin of a polarstereographic grid is at 90N  - that this routine will not work with PolarStereographic grids under any circumstance (even if the requested coverage area does not cover the north pole)
 
I’m assuming the answer is “Yes .. it won’t work” .. and no big deal if that is the case – but just want to make sure I don’t have some other problem.
 
Tks
 
ron

**Comment by davidh-ssec** [comment]
In the upcoming P2G 2.0 this is fixed by checking for data overlap in projection space (as opposed to lon/lat space). So if the projection supports the data (i.e. not trying to do south pole data on a north pole polar projection) data should be properly included. Doing this check in projection space takes longer, but is the only logical and correct choice without making assumptions about the data.
