### ISSUE TITLE
'cannot execute binary file' error on a Mac

### ISSUE THREAD

**Issue by andyprata** [davidh-ssec/polar2grid#114]
Hi,

I'm new to polar2grid and I've just downloaded the CSPP_IMAPP_POLAR2GRID_V2.0.tar.gz bundle from here: http://cimss.ssec.wisc.edu/cspp/download/index.php

I've followed the installation instructions however when I try to run any of the bash scripts I get this error:
```
dyn-49-127-66-246:~ andyprata$ viirs2gtiff.sh 
/Users/andyprata/Documents/PhD_2013_2014/python/CIMSS/polar2grid/polar2grid_v_2_0/bin/viirs2gtiff.sh: line 39:
/Users/andyprata/Documents/PhD_2013_2014/python/CIMSS/polar2grid/polar2grid_v_2_0/ShellB3/bin/python: cannot execute binary file
```
I believe I have the polar2grid home path correct:
```
dyn-49-127-66-246:~ andyprata$ echo $POLAR2GRID_HOME 
/Users/andyprata/Documents/PhD_2013_2014/python/CIMSS/polar2grid/polar2grid_v_2_0
```

I've also tried the following combinations to make the bash script executable:
```
chmod 777 viirs2gtiff.sh
sudo chmod 777 viirs2gtiff.sh
```
But I still get the same 'cannot execute binary file' error.  I'm on a Mac system (OS X 10.10.5 Yosemite) running the bash shell from Terminal.  Any help on this would be much appreciated.

Thanks,

Andy

**Comment by davidh-ssec** [comment]
Hi Andy,
The tarball available from the CSPP site is for 64-bit RHEL 5+ (or CentOS 5+) linux systems only. You won't be able to run that specific installation on a Mac. You can run Polar2Grid on a Mac, but we do not provide an all-in-one installation package like we do for our linux users. We have instructions on our documentation website for installing the individual python packages (does not include corrected reflectance software):

http://www.ssec.wisc.edu/software/polar2grid/installation.html#python-package-install

To do this on a mac I highly suggest using Anaconda or Macports or Homebrew to install a Python 2.7 environment and then run the commands mentioned in the documentation. Hope this helps.

**Comment by andyprata** [comment]
Hi David,

Thanks for such a quick response–I suspected that it was because I'm not on Linux.  I've tried installing the polar2grid from source by running `sudo python setup.py install` in here: `~/polar2grid-master/py/polar2grid` and I get the following error:
````
Installed /Users/andyprata/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/polar2grid-2.0.0-py2.7-macosx-10.6-x86_64.egg
Processing dependencies for polar2grid==2.0.0
Searching for polar2grid.core[all]
Reading https://pypi.python.org/simple/polar2grid.core/
Couldn't find index page for 'polar2grid.core' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for polar2grid.core[all]
error: Could not find suitable distribution for Requirement.parse('polar2grid.core[all]')
````
Do you think this issue is related to my Enthought Canopy installation of python or something else?

Thanks,

Andy

**Comment by davidh-ssec** [comment]
@andyprata, do you plan on modifying the code? Otherwise, is there a reason you are installing from the source code? Do the installation instructions at the webpage I provided not work for you?

I highly recommend **never** installing python packages using "sudo". Almost every command used for installing python packages has a `--user` flag that can be added so you install packages in a `~/.local` directory. This way you don't run things as root and you don't modify the installed python environment. If you don't need to modify the code I suggest installing things with the command from the webpage (with the added --user):

    pip install --user -i http://larch.ssec.wisc.edu/simple/ polar2grid[all]

This should find all of the core packages at our SSEC server. The reason your command failed is that our Polar2Grid packages are not made available through the normal and public PyPI package repository. If you need to modify the code I would suggest you install from source using this command:

    pip install --user -e -i http://larch.ssec.wisc.edu/simple/ .[all]

However, this will only install the main "polar2grid" package in development mode (edit the code and your installed package automatically uses these modifications), the other packages (polar2grid.core, polar2grid.viirs, etc) will be installed from the static packages on our server. You would have to install each package with a command like the above one at a time. If you do it this way then you wouldn't need the `-i URL` flag since you would be installing all the polar2grid dependencies yourself.

**Comment by andyprata** [comment]
Hi David,

At the moment I do not plan on modifying the code.  I was installing from source because the installation instructions on the website did not work for me.  Thanks for the tip–I will avoid using sudo in the future.  However, I'm still getting errors:
```
Andrews-MBP:~ andyprata$ pip install --user -i http://larch.ssec.wisc.edu/simple/ polar2grid[all]
Requirement already satisfied (use --upgrade to upgrade): polar2grid[all] in ./Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/polar2grid-2.0.0-py2.7-macosx-10.6-x86_64.egg
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages (from polar2grid[all])
Requirement already satisfied (use --upgrade to upgrade): numpy in ./Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages (from polar2grid[all])
Collecting polar2grid.core[all] (from polar2grid[all])
  DEPRECATION: Failed to find 'polar2grid.core' at http://larch.ssec.wisc.edu/simple/polar2grid.core/. It is suggested to upgrade your index to support normalized names as the name in /simple/{name}.
  The repository located at larch.ssec.wisc.edu is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host larch.ssec.wisc.edu'.
  Could not find a version that satisfies the requirement polar2grid.core[all] (from polar2grid[all]) (from versions: )
No matching distribution found for polar2grid.core[all] (from polar2grid[all])
```

**Comment by davidh-ssec** [comment]
Hi again Andy,

I'm sorry this has been so difficult. It's been a long time since I've actually tested these commands completely and it looks like some important things have changed with `pip` and how things need to be organized so they get installed. I was able to create a fresh environment with Anaconda (not needed for you since you have Canopy) and run this command to install everything:

    pip install --user --trusted-host larch.ssec.wisc.edu --extra-index-url http://larch.ssec.wisc.edu/simple/ polar2grid[awips,gtiff,remap,utils]

There are a couple things I should note about this command. It does not install the dependencies for the "NinJo" backend because there were some complications getting those dependencies to install with this method. It required some modifications on the server so thanks for pointing out that this doesn't work. It may try to install the "gdal" package as a dependency if not already installed in Canopy (I've never used Canopy, sorry) and this library is very complex so it may give you trouble compiling/installing if pip tries to do it. You should then be able to run most polar2grid commands like this:

    p2g_glue <frontend> <backend> ...

Let me know if any of this doesn't work. Sorry again.

**Comment by andyprata** [comment]
I really appreciate the support on this @davidh-ssec.  I do not need NinJo compatibility and  `pip` ran smoothly after running your suggested command.  I'm still reading through the docs, but what would be a good "test" command to see if the code is running properly?  I've tried this but I'm not sure if this means it's working properly:
```
Andrews-MBP:~ andyprata$ p2g_glue viirs gtiff -h
usage: p2g_glue [-h] [-v] [-l LOG_FN] [--debug] [--overwrite]
                [--exit-on-error]
                [--compositor-configs [COMPOSITOR_CONFIGS [COMPOSITOR_CONFIGS ...]]]
                {} {awips,binary,gtiff,hdf5,ninjo}
p2g_glue: error: argument frontend: invalid choice: 'viirs' (choose from )
```

**Comment by davidh-ssec** [comment]
You'll need to install the `polar2grid.viirs` package too (not automatically done with previous commands):

    pip install --user --trusted-host larch.ssec.wisc.edu --extra-index-url http://larch.ssec.wisc.edu/simple/ polar2grid.viirs

I think that the tarball you downloaded from the CSPP site should have some test data included that you should be able to run a simple command on. I was pretty sure the README came with instructions on the commands to run. You should be able to just swap out the parts about `viirs2gtiff.sh` with `p2g_glue viirs gtiff`. If not, I can find you some data to test with.

**Comment by andyprata** [comment]
Awesome!  Everything is working as expected now (I've installed `polar2grid.viirs` and `polar2grid.modis`).  And yes you're right the README was easy to work through.  Thank you so much for helping me out!

As an aside, I've also installed CentOS as a virtual machine (on VirtualBox) on my Mac, which I'm now using to generate corrected reflectance hdfs and GeoTIFFs (the true colour MODIS/VIIRS scripts are fantastic–thank you).  Just out of curiosity, do you think `crefl` will be re-written for a Mac system in the future?

**Comment by davidh-ssec** [comment]
The crefl software is actually buildable on Mac (I develop P2G on mac). However, it depends on some libraries that don't come with Mac by default so you usually have to get them from somewhere else. I'll see if I can get you something that works (I'll talk to some other people to see if I'm missing any options). If you want to try it yourself you can checkout the code and look at the `modis_crefl` and `viirs_crefl` directories. You should be able to run `LDFLAGS="-I ~/opt/include -L ~/opt/lib" make` for both VIIRS and MODIS versions. You would need to replace `~/opt/` with the location where you have HDF4, HDF5, libjpeg, zlib libraries installed (I think that's all of them).

I'll let you know if I find a better way to install them. In the future I hope to rewrite these programs in python so they can be more easily distributed.

**Comment by andyprata** [comment]
A "pycrefl" would be great. I was able to compile `crefl` and `cviirs`.  It was actually pretty straight forward with Macports.  I used this command to install the dependencies:
```
sudo port install gdal +hdf4 +hdf5 +netcdf
```
Then from inside the `modis_crefl` and `viirs_crefl` directories I ran your suggested command with the appropriate paths for a Macports installation:
```
LDFLAGS="-I /opt/local/include -L /opt/local/lib" make
```
So now I've got Mac compiled executables for `crefl` and `cviirs`.  I then copied them into `$POLAR2GRID_HOME/bin` and have overwritten the old executables.  I then added the following to my `bash_profile`:
```
# Add home path for polar2grid
export POLAR2GRID_HOME=$HOME/polar2grid_v_2_0

# Add all polar2grid scripts to PATH
export PATH=$POLAR2GRID_HOME/bin:$PATH

# Point gdal utilities to the proper data location
export GDAL_DATA=/opt/local/share/gdal
```
So now `crefl` (and `cviirs`) are working:
```
dyn-49-127-66-246:A2015308_0600 andyprata$ crefl
Usage:
crefl [--verbose] [--1km|--500m] [--nearest] [--toa|--sealevel]
      [--gzip] [--maxsolz=angle] [--range=min,max] [--overwrite|--append]
      [--bands=<band1,band2,band3,...>] --of=<output file>
      <MOD021KM|MOD02CRS|MOD09CRS file> [<MOD02HKM file>] [<MOD02QKM file>]
Version 1.7.1, compiled Nov  9 2015 12:59:38.
```
I now wanted to see if I could use the `crefl` frontend and `gtiff` backend to output the true colour geotiff of the following MODIS swath:
```
dyn-49-127-66-246:A2015308_0600 andyprata$ ls
MYD021KM.A2015308.0600.005.NRT.hdf
MYD02HKM.A2015308.0600.005.NRT.hdf
MYD02QKM.A2015308.0600.005.NRT.hdf
MYD03.A2015308.0600.005.NRT.hdf
```
So I ran:
```
p2g_glue crefl gtiff -f MYD0{21KM,2HKM,2QKM,3}.A2015308.0600.*.hdf
```
And I get the following error:
```
ERROR    : Error running modis crefl
ERROR    : Could not create modis crefl files from SDRs
ERROR    : crefl frontend failed to load and sort data files (see log for details)
```
I've had a look through the `crefl2gtiff_fail.log` file and it seems that I'm not pointing to the right `python` i.e. this line:
```
Cannot open file /Users/andyprata/Library/Enthought/Canopy_64bit/bin/tbase.hdf.
```
That directory does not exist.  It should be looking in the the same `bin` directory as my `python` installation, right?
```
dyn-49-127-66-246:~ andyprata$ which python
/Users/andyprata/Library/Enthought/Canopy_64bit/User/bin/python
```

**Comment by davidh-ssec** [comment]
Oops sorry I forgot about the ancillary files. You can get the cviirs one here: http://www.ssec.wisc.edu/~davidh/polar2grid/viirs_crefl/CMGDEM.hdf and the crefl (modis) one here: http://www.ssec.wisc.edu/~davidh/polar2grid/modis_crefl/tbase.hdf

You should also make sure that the crefl executables are on your PATH and then you can set the base path for the ancillary files with `P2G_CVIIRS_ANCPATH` and `P2G_CMODIS_ANCPATH`. Also note that the cviirs program comes with an additional executable `h5SDS_transfer_rename`, this also has to be discoverable on your PATH. I would suggest either pointing your PATH to the build directories in your checked out version of the code where you compiled them or copying them somewhere outside of the original tarball you downloaded (to avoid confusion). You also don't need to use the `POLAR2GRID_HOME` environment variable since you are using the `p2g_glue` command directly and setting up your own python environment. It looks like you know some stuff about using the command line so I'm hoping the stuff about PATH makes sense.

**Comment by andyprata** [comment]
Ah ok!  I think I'm very close.  I've added `crefl` and `cviirs` to my PATH.  I've also set the ancillary files using `P2G_CVIIRS_ANCPATH ` and `P2G_CMODIS_ANCPATH `.  Everything runs smoothly now with:
```
p2g_glue crefl gtiff -f MYD0{21KM,2HKM,2QKM,3}.A2015308.0600.*.hdf
``` 
However, I still don't have that illusive true colour tiff:
```
dyn-49-127-66-246:A2015308_0600 andyprata$ ls
MYD021KM.A2015308.0600.005.NRT.hdf
MYD02HKM.A2015308.0600.005.NRT.hdf
MYD02QKM.A2015308.0600.005.NRT.hdf
MYD03.A2015308.0600.005.NRT.hdf
a1.15308.0600.crefl.1000m.hdf
a1.15308.0600.crefl.250m.hdf
a1.15308.0600.crefl.500m.hdf
aqua_modis_modis_crefl01_1000m_20151104_060000_wgs84_fit.tif
aqua_modis_modis_crefl01_250m_20151104_060000_wgs84_fit.tif
aqua_modis_modis_crefl03_1000m_20151104_060000_wgs84_fit.tif
aqua_modis_modis_crefl04_1000m_20151104_060000_wgs84_fit.tif
crefl2gtiff_20151104_060000.log
```
So I tried this (because now I have the corrected reflectance hdfs):
```
p2g_glue crefl gtiff -f a1.15308.0600.crefl.{1000m,500m,250m}.hdf
```
But I get this error:
```
ERROR    : Frontend data extraction failed (see log for details)
```
I checked the log file and here's where it gets stuck:
```
[2015-11-09 15:25:56,976] : PID  28574 : DEBUG    : crefl2gtiff : main : Frontend data extraction exception:
Traceback (most recent call last):
  File "build/bdist.macosx-10.6-x86_64/egg/polar2grid/glue.py", line 300, in main
    scene = f.create_scene(**args.subgroup_args["Frontend Swath Extraction"])
  File "/Users/andyprata/Library/Python/2.7/lib/python/site-packages/polar2grid/crefl/crefl2swath.py", line 779, in create_scene
    lon_swath = products_created[lon_product_name] = self.create_raw_swath_object(lon_product_name, None)
  File "/Users/andyprata/Library/Python/2.7/lib/python/site-packages/polar2grid/crefl/crefl2swath.py", line 712, in create_raw_swath_object
    file_reader = self.file_readers[file_type]
KeyError: 'file_type_geo'
```

**Comment by davidh-ssec** [comment]
Awesome to here you got it. Nice job finding the way to call it for true color. To use our default false color image and still create the true color you can do:

    p2g_glue crefl gtiff true_color false_color --true-color --false-color -f ...

I know this doesn't make much sense. It'll be better in future versions.

**Comment by andyprata** [comment]
Yep that command works too.  Thanks again, and thanks for an excellent piece of software!

**Comment by davidh-ssec** [comment]
No problem. Thanks for being patient and testing this all out.
