### ISSUE TITLE
How to use rescale to invert one of the RGB bands

### ISSUE THREAD

**Issue by songhan89** [davidh-ssec/polar2grid#118]
Hi David,

Sorry i have been reading the documentation and still don't really understand how to make a user-defined rescaler. Basically, my intention is to make a VIIRS I01-I02-I05(inverse) RGB image. 

I have setup this rgb.conf and able to generate a I01-I02-I05 RGB with no problems. But how do i use the rescaler to invert the just the Blue Channel - I05 alone? Would you be able to provide me with some example codes? 

Thank you very much.

**Comment by davidh-ssec** [comment]
Hi @songhan89. I'm sorry but I don't think this is possible right now. At least not without editing some python code. If you are comfortable doing that then I can guide you in adding something that might do what you want. However, I should warn you that I hope to replace the current method for creating RGBs in the future since it is difficult to accomplish most custom RGBs.

Another option you could use is to create your own rescale configuration and create each individual crefl geotiff image. This would let you individual configure how each is scaled. After that you could use `gdal_merge.py` utility provided by the GDAL library to merge them in to one RGB image.

**Comment by songhan89** [comment]
Hi David,

Thanks for the quick response. I look forward to the update.

For the time being, the second option sounds good to me. Two questions though:

1.  I'm still not exactly sure if the following is the right thing to add in rescale.ini, supposing I'm adding the option to invert the Brightness Temperature for I05. Could you advise me on this?

```
[rescale:invert_brightness_temperature] ??
data_kind=brightness_temperature
method=linear
min_in=230
max_in=310
flip=True
```

2. What would be the appropriate argument to pass in for the viirs2gtiff.sh ??

`viirs2gtiff.sh smokehaze_rgb --compositor-configs smokehaze_composites.conf --rescale-configs ????  -f /pathtofiles/ -p i01 i02 i05`

**Comment by davidh-ssec** [comment]
If you are editing the `rescale.ini` file in the Polar2Grid source then you don't need the `--rescale-configs` argument. However I suggest you make your own separate config file (ex. `my_rescale.ini`) then you would specify `--rescale-configs rescale.ini /path/to/my_rescale.ini`. This will apply your configuration on top of the one provided by P2G. If you only want to use your configuration and not the builtin one then it would be `--rescale-configs /path/to/my_rescale.ini`.

Also, you in your rescale configuration you may want to be more specific for what products should use this inverted rescaling. The way you have it now P2G doesn't know whether to use your inverted scaling or the default scaling for brightness temperatures. You should maybe add something like `product_name`:

```
[rescale:invert_brightness_temperature] ??
data_kind=brightness_temperature
product_name=i05
method=linear
min_in=230
max_in=310
flip=True
```

This way only i05 brightness temperatures will get scaled this way. I hope this helps.

**Comment by songhan89** [comment]
Thanks David for the useful info! I'll try it out.
