### ISSUE TITLE
VIIRS L1B product options list DNB instead of enhancement options

### ISSUE THREAD

**Issue by kathys** [davidh-ssec/polar2grid#128]
Using the rc6 tarball, I used --list-products on my VIIRS 2.0 L1B test input data.  The list of options were:  

polar2grid.sh viirs_l1b gtiff --list-products -f ../l1b
INFO     : Initializing reader...
DNB
dnb_lunar_zenith_angle
dnb_moon_illumination_fraction
dnb_solar_zenith_angle
i01
i02
i03
i04
i05
i_satellite_azimuth_angle
i_satellite_zenith_angle
i_solar_azimuth_angle
i_solar_zenith_angle
m01
m02
m03
m04
m05
m06
m07
m08
m09
m10
m11
m12
m13
m14
m15
m16
satellite_azimuth_angle
satellite_zenith_angle
solar_azimuth_angle
solar_zenith_angle
-----------------------

The -p DNB option does not work, but using -p adaptive_dnb dynamic_dnb does.  Also, is this the complete option list?

**Comment by davidh-ssec** [comment]
That list should include all of the "from the file" datasets that you can get and will include a few more things in the next tarball because I'll be updating the version of satpy. This does not include composites that could be generated however like true_color and false_color which would be useful. Without some special handling of it though it would also include all the other composites that satpy could produce which there are at least 2 new ones.

This has made me discover a bug in satpy though so I'll need to work on that before I have a working solution. Either way we'll need to discuss what you want this to list. I could hardcode the list also, but in the future we'll really want it auto-generated.
