### ISSUE TITLE
How do i generate modis_crefl0[1-4]_250m	?

### ISSUE THREAD

**Issue by songhan89** [davidh-ssec/polar2grid#134]
Hi David,

I noticed that when i run 
`crefl2gtiff.sh -p modis_crefl01_250m modis_crefl02_250m modis_crefl03_250m modis_crefl04_250m -g wgs_fit_250 -f *.hdr`

It fails to generate the 250m crefl geotiffs. Something which i intend to use it for custom rgb composition using `gdal_merge.py`

However, it runs fine when i use the -flag `true_color false_color`. But the .tif files generated from these flags seem to be 1000m crefl instead of 250m crefl. 

How do i get the 250m crefl .tif ?

Thanks.

**Comment by davidh-ssec** [comment]
The best way for me to help would be if you could provide the error message you get from the first command you ran. Providing me the log file that Polar2Grid produces while executing this command would give me the most information.  Without knowing the error message there isn't much I can do.

Loading that resolution of data is fairly untested although I would have expected it to work. The true and false color flags are preset band selections that produce ratio-sharpened versions of the 1000m bands using band 1 at 250m resolution. I would assume that since we load band 1 at 250m resolution that loading any of the other 250m resolution bands would work too.

**Comment by davidh-ssec** [comment]
I just looked at the code and some example crefl HDF4 files and noticed that in the 250m file only band 1 and 2 are at the 250m resolution. So even though they include band 3 and 4 in the 250m file they are at their original 500m resolution. This means Polar2Grid is configured incorrectly to use these products as I assumed that all the datasets in the 250m crefl file would be at the 250m resolution.

My suggestion would be to load the 500m versions of band 3 and 4. Once they have been resampled to the output grid it won't matter that the inputs had different sizes since the grid will be the same size.

**Comment by songhan89** [comment]
Hi David,

Sorry for the late reply. I ran the following cmd:

`crefl2gtiff.sh -f t1.17065.1151*.hdf -p modis_crefl01_250m modis_crefl02_250m modis_crefl03_500m modis_crefl04_500m`

But somehow it still didn't work. Please see the log attached.
[Uploading crefl2gtiff_20170306_115100.txt…]()

**Comment by davidh-ssec** [comment]
@songhan89 I'm so sorry I lost track of this issue. I think the easiest thing will be to wait for the version 2.1 release which we hope to have out in the next week or so.

**Comment by songhan89** [comment]
@davidh-ssec,

I tried to revisit this issue. So I've entered the following cmd

`crefl2gtiff.sh -p modis_crefl01_250m modis_crefl02_250m modis_crefl03_250m modis_crefl04_250m -g wgs84_fit_250 -f *.hdf `

It seems that the issues are still persisting in v2.1. Please see the log attached.

Thanks.

[crefl2gtiff_20170724_151400.txt](https://github.com/davidh-ssec/polar2grid/files/1170508/crefl2gtiff_20170724_151400.txt)

**Comment by davidh-ssec** [comment]
@songhan89 I'm sorry I thought I had fixed this in version 2.1. Luckily, the fix in version 2.1 is not very difficult and you can probably do it yourself by editing your version of Polar2Grid. You can find the file to edit in the v2.1 release here: `polar2grid/common/ShellB3/lib/python2.7/site-packages/polar2grid/crefl/crefl2swath.py`. You can then edit it according to the diff on this page: https://github.com/davidh-ssec/polar2grid/commit/b8bd6678b0bcfa7de825a28b5323faaf6f5c8389
