### ISSUE TITLE
iasi2fbf used by Dual Regression retrieval should be turned into an alpha polar2grid.iasi FE

### ISSUE THREAD

**Issue by rayg-ssec** [davidh-ssec/polar2grid#57]
The Iasi code metahoard.iasi.fbf (aka iasi2fbf) has too many dependencies. Refactoring it into a standalone package is a subset of creating a polar2grid.iasi frontend. iasi2fbf code should be recast as an alpha version of a polar2grid.iasi entry point, even if the module isn't complete enough to include in an upcoming release. 

Packaging in the dual regression bundle can be done similarly to the polar2grid.viirs module use in the CSPP package.

This will be done on the cris_rayg_201303 branch since the two instruments are similar - eventually a polar2grid.interferometer common module may be shared between the two - for instance BT slice generation code.

**Comment by davidh-ssec** [comment]
With the changes to polar2grid for v2.0 the iasi package went through a few changes. It no longer attempts (or has a placeholder) for a P2G Frontend. Instead it sits in the repository, as a polar2grid package with no other polar2grid dependencies. I have no problem leaving this package in the repository since it may be useful to polar2grid in the future. @rayg-ssec, if you think this may be better in another repository feel free to remove it from the develop branch. There is also a `hyperspectral` branch that has less modified code (closer to where @rayg-ssec left it) which includes the CrIS branch which is in a similar state. @rayg-ssec, any thoughts?

**Comment by rayg-ssec** [comment]
I think I should probably 
- clone the repo
- trim it down to just Iasi code and rearrange it
- push it to a new repo under my github account as iasi_tools or equivalent

Sound reasonable?

**Comment by davidh-ssec** [comment]
Sure, go with what you feel. If we need an iasi frontend in the future we can just make the tools a dependency.
